### ISSUE TITLE
S2 duplicate results from 2021, but not in 2022

### ISSUE THREAD

**Issue by Kongstad** [Element84/earth-search#25]
Hi,

I am trying to understand a weird issue here and was hoping you could help me figure it out.
I appreciate your time.

I have been downloading S2 images over Denmark which are subsequently cut down to farm field polygons from August 2021 to April 2022.  I have noticed that there seem to be double data occurances for images captured in 2021, but not in 2022. Below I have attached an example of some field level images:
![e841](https://github.com/Element84/earth-search/assets/33096163/9a1303b7-fd22-422d-86c9-0983592ce463)

Not only are there double occurances, but there also seem to be differences between the “duplicates”. Some occur darker/brighter and for the snow covered images one seems to be more blue.
I have double checked on Sentinel-hub EO browser to understand the tiles and the fields do reside inside an area of 4 tiles overlapping as seen in the image below:
![e842](https://github.com/Element84/earth-search/assets/33096163/f54aec1f-d3a6-4ff7-9594-6abdd8e6111a)
But if that was the cause of the problem, there should be 4 occurances and it still does not explain the issue of why it happens in 2021 and not in 2022.
When I check Sentinel-hub again for the February 28th occurance, it looks identical:
![e843](https://github.com/Element84/earth-search/assets/33096163/3117309d-2af2-4b99-97db-f98747fd72cb)
So according to Sentinel-hub the data should be similar.

I then did a second experiment where I compare E84 S2 data with data from Microsoft Planetary Computer and they do not seem to have the same duplicate data. See image below with E84 on the left and MSPC on the right:
![e84_mspc](https://github.com/Element84/earth-search/assets/33096163/34eb291e-b8a4-482d-b34f-0a950aeb3615)

What am I missing here? Is it an E84 API issue? Is there a general change in data between 2021/2022 that just is not reflected differently on Sentinel-hub?

Appreciate any input.
Thank you for your time.

**Comment by gadomski** [comment]
Hello, thanks for your question. I don't know _exactly_ why the L2 scenes are duplicated, but we are currently reprocessing _all_ Sentinel-2 scenes -- see [this email](https://us13.campaign-archive.com/?u=a7a7fcb1ce46c4d001fc76289&id=cf7934577f) for more information. It's likely that the problem will be fixed by the reprocessing. I'd suggest waiting until the reprocessing is complete, then re-running your experiment -- if the issue persists after reprocessing, we can dig in deeper then.

Thanks for the issue report! For more information on the reprocessing, you can sign up for our mailing list [here](https://element84.us13.list-manage.com/subscribe?u=a7a7fcb1ce46c4d001fc76289&id=38266ef009).

**Comment by Kongstad** [comment]
Thank you for this information. Very helpful and I have signed up to your news letter.
