### ISSUE TITLE
When will sentinel-2-pre-c1-l2a items be deleted? 

### ISSUE THREAD

**Issue by keithpeck** [Element84/earth-search#45]
Will files in `s3://e84-earth-search-sentinel-data/sentinel-2-pre-c1-l2a` be deleted when corresponding `s3://e84-earth-search-sentinel-data/sentinel-2-c1-l2a` items are processed? Or in bulk at some point in the future.

Thanks

**Comment by matthewhanson** [comment]
Hello @keithpeck They will be deleted in bulk at some point in the future, but will be available at least through the end of the year.

The goal of this collection was to backfill some data that ESA hasn't processed yet, but with our up to date COG process that doesn't apply the offset to the COGs.  It's not ideal since they aren't baseline 05.00+ or higher but it is better than mixing the `sentinel-2-c1-l2a` and `sentinel-2-l2a` collections.

**Comment by keithpeck** [comment]
Hi @matthewhanson, thanks for the answer!
