### ISSUE TITLE
Incomplete search results for sentinel-2-l2a cogs.

### ISSUE THREAD

**Issue by jirikadlec2** [Element84/earth-search#50]
Hello, I am having issues finding a Sentinel-2 COG (cloud optimized GeoTiff) using pystac_client for 2024-03-18 33UVR , although I checked that the data exists in COG GeoTiff format on S3 on the **sentinel-cogs** bucket:

aws s3 ls s3://sentinel-cogs/sentinel-s2-l2a-cogs/33/U/VR/2024/3/S2A_33UVR_20240318_0_L2A/

Python code to reproduce the issue:

```
import datetime
import pystac_client
client = pystac_client.Client.open('https://earth-search.aws.element84.com/v1')
search = client.search(collections=["sentinel-2-l2a"], bbox="15.027,49.920,15.034,49.926",datetime=[datetime.datetime(2024,3,18), datetime.datetime(2024,3,19)])
print(list(search.items()))
```

results in: `[<Item id=S2A_33UWR_20240318_0_L2A>]`

However this is incorrect, the expected result is two items:` [<Item id=S2A_33UVR_20240318_0_L2A>,<Item id=S2A_33UWR_20240318_0_L2A>]`

because both scenes **S2A_33UVR_20240318_0_L2A** and **S2A_33UWR_20240318_0_L2A** intersect with the bounding box "15.027,49.920,15.034,49.926"

Any suggestions how to fix the issue?

**Comment by fmariv** [comment]
Same issue here, but trying to download images from the last month, it can't find anything although there is data from today. From before, it doesn't give me a problem.

**Comment by fmariv** [comment]
@philvarner thanks for the quick response. Unfortunately, I have tried moving to the new collection `sentinel-2-c1-l2a` and I get the same error. Basically, I'm trying to access Sentinel-2 images using your STAC catalog and with packages like `stac_client` or `odc-stac`. The error is that, while I can find data for before August, for this last month of August I cannot find anything. The link that you have provided me makes sense and it seems that it could be the reason, but it also seems strange to me because if I search for the data through STAC Browser I do find it.

**Comment by philvarner** [comment]
What is the exact code and query you're running? When I run:

```
https://earth-search.aws.element84.com/v1/search?collections=sentinel-2-c1-l2a&datetime=2024-08-01T00:00:00Z/2024-08-31T00:00:00Z
```

I get 

```

  "type": "FeatureCollection",
  "stac_version": "1.0.0",
  "stac_extensions": [
    
  ],
  "context": {
    "limit": 10,
    "matched": 341500,
    "returned": 10
  },
  "numberMatched": 341500,
  "numberReturned": 10,

```

**Comment by fmariv** [comment]
Here is the relevant code:

```python
# [my class...]

self.catalog = pystac_client.Client.open(self.url, modifier=self.modifier) # url = "https://earth-search.aws.element84.com/v1"

    def search_stac(self):
        items = self.catalog.search(
            bbox=self.aoi,
            datetime=self.datetime,  # here is for the last month, for July I can find data
            collections=self.collection,   # here is sentinel-2-l2a or sentinel-2-c1-l2a
            query=self.query,  # custom query
        ).item_collection()

        if len(items) == 0:
            print(
                f"No images found for {self.datetime} in {self.collection} collection"
            )
            return None

        return items

# [ ... more class ...]
```

The problem arises when searching using the `pystac_client` library, so that it does not find items and then I cannot load them with `odc-stac`. The version of `pystac_client` = 0.7.6.

**Comment by philvarner** [comment]
@fmariv what's the bbox, datetime, and query that that you get no results for?

**Comment by fmariv** [comment]
Apologies, I attach the variables:

```python
# [my class...]

self.catalog = pystac_client.Client.open(self.url, modifier=self.modifier) # url = "https://earth-search.aws.element84.com/v1"

    def search_stac(self):
        items = self.catalog.search(
            bbox=[ 2.0524977 41.3170353  2.2283555 41.4679135],
            datetime=('2024-08-01', '2024-08-28'),
            collections=self.collection,   # here is sentinel-2-l2a or sentinel-2-c1-l2a
            query=query,  # custom query, see below
        ).item_collection()

        if len(items) == 0:
            print(
                f"No images found for {self.datetime} in {self.collection} collection"
            )
            return None

        return items

# [ ... more class ...]

query={'eo:cloud_cover': {'lt': 100}, 's2:vegetation_percentage': {'lt': 100}, 's2:dark_features_percentage': {'lt': 100}, 's2:cloud_shadow_percentage': {'lt': 100}, 's2:water_percentage': {'lt': 100}, 's2:not_vegetated_percentage': {'lt': 100}, 's2:snow_ice_percentage': {'lt': 100}, 's2:nodata_pixel_percentage': {'lt': 100}}

```

**Comment by philvarner** [comment]
@fmariv 

The issue seems to be the use of the `s2:dark_features_percentage` property in the query. The source metadata property used for it is missing for some items, e.g., https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/31/T/DF/2024/7/S2A_31TDF_20240725_0_L2A/granule_metadata.xml, so it's not populated into the metadata.  For August, there are no items in the results obtained with the other parameters that have it, whereas in July there are.

There's no way that I can think of the get around this issue. My suggestion is to remove it entirely, since most scenes have a very low dark_features_percentage so it won't affect the search results much. If there are scenes that it matters for, you should filter them out of the results after getting them from the server.

**Comment by philvarner** [comment]
Original issue is resolved, closing.

**Comment by fmariv** [comment]
Thank you so much for your time!
